### ISSUE TITLE
devDependencies are saved as dependencies

### ISSUE THREAD

**Issue by BloodyHell** [peerigon/updtr#13] opened 2015-12-02 15:13 UTC
The following line of code presents line 92 of run.js, version 0.1.4:

``` javascript
info.saveCmd = info.type === "devDependencies" ? "--save-dev" : "--save";
```

If I follow the source correctly, this is used to make the difference between your dependencies being saved in devDependencies or dependencies.

But when I use the plugin all the dependencies are always placed in "dependencies", even if they are originally contained in "devDependencies".

In the test file there is also no mention of devDependencies :smile:.

Anyone else facing the same issue that can confirm this? I'm at the moment unable to pull the code and add tests to check thoroughly.

**Comment by matthaias** [comment] 2015-12-02 19:10
With which version of npm? You need >= 2.5 since the package type was added to this version, should be listed in the `package.json`.

But yes, we should add tests to check this and maybe a check when starting `updtr` if the npm version is >= 2.5.

I did a short check:

```
➜ npm i servus.js@0.0.1 --save
updtrtest@0.0.1 
└── servus.js@0.0.1

➜ npm i xunit-file@0.0.1 --save-dev
updtrtest@0.0.1 
└── xunit-file@0.0.1

➜ updtr
Found 2 outdated modules

Starting to update your modules...
1/2 	 ● servus.js 0.0.2 success
2/2 	 ● xunit-file 0.0.9 success

Finished
➜ cat package.json
{
  "name": "updtr test",
  "version": "0.0.1",
  "description": "updtr test",
  "main": "index.js",
  "devDependencies": {
    "xunit-file": "0.0.9"
  },
  "scripts": {
    "test": "mocha -R spec"
  },
  "dependencies": {
    "servus.js": "0.0.2"
  }
}
```

So for me this works. Can you please check your npm version?

**Comment by BloodyHell** [comment] 2015-12-03 08:45
My bad, checked the npm version and it was sorely outdated.
After updating to >= 2.5 Updtr works just fine. Thanks! :+1:

**Comment by fkrauthan** [comment] 2016-07-12 18:17
Can we reopen this issue? I run into exactly the same issue. I am using updtr version 0.2.1, npm version 3.8.6 and node version 5.11.1

When I run updtr it moves devDependencies into dependencies

**Comment by matthaias** [comment] 2016-07-14 06:40
Sure. I hope we can check this soon enough.

**Comment by fkrauthan** [comment] 2016-07-14 06:50
Sorry it not moves it it just re adds them as regular dependency. So devDependency contains the old version dependencies contains the new version.

**Comment by matthaias** [comment] 2016-07-14 07:16
Good to know.

**Comment by matthaias** [comment] 2016-11-13 10:39
@fkrauthan i still can't reproduce this behavior, sorry. Can you please to check it again? Otherwise i would be happy to receive a pull request solving this problem. Thanks?

**Comment by jhnns** [comment] 2018-03-25 18:00
Has been fixed with the rewrite

**Closed** 2018-03-25 18:00 UTC
